CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	username TEXT COLLATE NOCASE NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	avatar TEXT,
	date_created TEXT NOT NULL, 
	role_id INTEGER FOREIGN KEY NOT NULL,
	signature TEXT
);

CREATE TABLE IF NOT EXISTS roles (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS threads (
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	author_id INTEGER FOREIGN KEY NOT NULL,	
	date_created TEXT NOT NULL,
	category_id INTEGER FOREIGN KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
	id INTEGER PRIMARY KEY,
	body TEXT NOT NULL,
	author_id INTEGER FOREIGN KEY NOT NULL,
	date_created TEXT NOT NULL,
	thread_id INTEGER FOREIGN KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS thread_likes (
	thread_id INTEGER FOREIGN KEY NOT NULL,
	user_id INTEGER FOREIGN KEY NOT NULL,
	PRIMARY KEY (thread_id, user_id),
	thread_like BOOLEAN NOT NULL 
);

CREATE TABLE IF NOT EXISTS comment_likes (
	comment_id INTEGER FOREIGN KEY NOT NULL,
	user_id INTEGER FOREIGN KEY NOT NULL,
	PRIMARY KEY (comment_id, user_id),
	thread_like BOOLEAN NOT NULL 
);

CREATE TABLE IF NOT EXISTS categories (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);
 
CREATE TABLE IF NOT EXISTS images (
	id INTEGER PRIMARY KEY,
	image_path TEXT NOT NULL,
	comment_id INTEGER FOREIGN KEY,
	thread_id INTEGER FOREIGN KEY
);

CREATE TABLE IF NOT EXISTS sessions (
	id INTEGER PRIMARY KEY,
	session_id TEXT NOT NULL,
	user_id INTEGER FOREIGN KEY NOT NULL
);









